
// This file now contains core type definitions that are NOT dependent on i18n data.
// Definitions that rely on labels from JSON (like SIZES, ALIGNMENTS array constants)
// will be generated by the I18nProvider and accessed via context.

import type { LanguageCode } from '@/i18n/config';

export type LocalizedString = string | { [key in LanguageCode]?: string } | { en: string; [key: string]: string };

export type AbilityName = 'strength' | 'dexterity' | 'constitution' | 'intelligence' | 'wisdom' | 'charisma' | 'none';

export interface AbilityScores {
  strength: number;
  dexterity: number;
  constitution: number;
  intelligence: number;
  wisdom: number;
  charisma: number;
}

export interface CharacterClass {
  id: string; // Instance ID of this class level entry
  className: DndClassId | ''; // kebab-case ID of the class definition
  level: number;
}

export interface CustomSynergyRule {
  id: string; // Unique ID for this rule
  targetSkillName: string; // Skill ID this rule applies to
  ranksInThisSkillRequired: number;
  bonusGranted: number;
}

export interface Skill {
  id: string; // Skill ID (e.g., "climb", "knowledge-arcana")
  ranks: number;
  miscModifier: number;
  isClassSkill?: boolean;
}

export interface FeatPrerequisiteDetails {
  bab?: number;
  abilities?: Partial<Record<Exclude<AbilityName, 'none'>, number>>;
  skills?: Array<{ id: string; ranks: number }>; // Skill ID
  feats?: string[]; // Feat IDs
  casterLevel?: number;
  classLevel?: { classId: DndClassId | string; level: number }; // Class ID
  raceId?: DndRaceId | string; // Race ID
  alignment?: string; // Alignment ID or generic keyword
  special?: LocalizedString;
  specialConditions?: Array<{
    type: string;
    [key: string]: any;
  }>;
}

export interface FeatEffectScalingSpecificLevel {
  level: number;
  value: any;
  tierName?: LocalizedString;
}

export interface FeatEffectScaling {
  classId: DndClassId | string; // Class ID
  specificLevels: FeatEffectScalingSpecificLevel[];
  valuePerLevel?: number;
}

export interface AggregatedFeatEffectBase {
  sourceFeat?: LocalizedString;
  condition?: string;
  isActive?: boolean;
}


export interface SkillEffectDetail {
  type: "skill";
  skillId: string | null; // Skill ID or null for specialization
  value: number;
  bonusType?: "competence" | "circumstance" | "racial" | "untyped" | "insight";
  scaleWithClassLevel?: FeatEffectScaling;
}

export interface NoteEffectDetail {
  type: "note";
  text: LocalizedString;
}

export interface AbilityScoreEffect {
  type: "abilityScore";
  ability: Exclude<AbilityName, 'none'>;
  value: number | string; // string for "WIS", "INT", "CHA"
  bonusType?: "enhancement" | "inherent" | "morale" | "competence" | "circumstance" | "size" | "untyped";
  scaleWithClassLevel?: FeatEffectScaling;
}

export interface SavingThrowEffect {
  type: "savingThrow";
  save: SavingThrowType | "all";
  value: number | "CHA"; // CHA for Paladin Divine Grace
  bonusType?: "resistance" | "luck" | "morale" | "competence" | "circumstance" | "racial" | "insight" | "untyped";
  scaleWithClassLevel?: FeatEffectScaling;
}

export interface AttackRollEffect {
  type: "attackRoll";
  value: number | "CHA"; // CHA for Paladin Smite
  bonusType?: "untyped" | "enhancement" | "competence" | "luck" | "insight" | "circumstance" | "focus";
  appliesTo: "all" | "melee" | "ranged" | "unarmed" | "grapple" | "SPEC" | `weaponCategory:${string}` | `weaponName:${string}`;
  weaponId?: string; // Specific weapon definition ID
  rangeLimit?: number;
  scaleWithClassLevel?: FeatEffectScaling;
}

export interface DamageRollEffect {
  type: "damageRoll";
  value: number | string; // number or dice string like "1d6" or "classLevel:paladin"
  bonusType?: "untyped" | "enhancement" | "competence" | "luck" | "precision" | "circumstance" | "specialization";
  appliesTo?: "all" | "melee" | "ranged" | "unarmed" | "grapple" | "SPEC" | `weaponCategory:${string}` | `weaponName:${string}`;
  weaponId?: string; // Specific weapon definition ID
  rangeLimit?: number;
  scaleWithClassLevel?: FeatEffectScaling;
}

export interface ArmorClassEffect {
  type: "armorClass";
  value: number | "WIS" | "INT" | "CHA";
  acType: "dodge" | "armor" | "shield" | "natural" | "deflection" | "insight" | "circumstance" | "untyped" | "monk_wisdom" | "monkScaling" | "other_feat_bonus";
  bonusType?: "untyped" | "dodge" | "armor" | "shield" | "natural" | "deflection" | "insight" | "sacred" | "profane" | "competence" | "circumstance";
  appliesToScope?: ("normal" | "touch" | "flatFooted")[];
  scaleWithClassLevel?: FeatEffectScaling;
}

export interface HitPointsEffect {
  type: "hitPoints";
  value: number;
  perLevel?: boolean;
  bonusType?: "untyped";
  scaleWithClassLevel?: FeatEffectScaling;
}

export interface InitiativeEffect {
  type: "initiative";
  value: number;
  bonusType?: "competence" | "insight" | "untyped";
  scaleWithClassLevel?: FeatEffectScaling;
}

export interface SpeedEffect {
  type: "speed";
  speedType: SpeedType | "all";
  modification: "bonus" | "setAbsolute" | "penalty";
  value: number;
  bonusType?: "enhancement" | "untyped";
  scaleWithClassLevel?: FeatEffectScaling;
}

export interface ResistanceEffect {
  type: "resistance";
  resistanceTo: string;
  value: number;
  isDamageReduction?: boolean;
  bypassedBy?: string[];
  bonusType?: "resistance" | "untyped";
  scaleWithClassLevel?: FeatEffectScaling;
}

export interface CasterLevelCheckEffect {
  type: "casterLevelCheck";
  value: number;
  forEvent?: "spellResistance" | "dispel" | "all";
  bonusType?: "untyped" | "competence";
  scaleWithClassLevel?: FeatEffectScaling;
}

export interface SpellSaveDcEffect {
  type: "spellSaveDc";
  school?: string | "all" | "SPEC"; // School ID or "all" or "SPEC" for specialization
  value: number;
  bonusType?: "untyped";
  scaleWithClassLevel?: FeatEffectScaling;
}

export interface TurnUndeadEffect {
  type: "turnUndead";
  property: "attempts" | "effectiveLevel" | "damage" | "checkBonus";
  value: number;
  bonusType?: "untyped";
  scaleWithClassLevel?: FeatEffectScaling;
}

export interface GrantsAbilityEffectUses {
  per: "day" | "encounter" | "week"; // Added "week" for Quivering Palm
  value?: number | "levelBased" | "abilityModBased" | "scaled" | "customPool"; // Added customPool
  basedOnAbility?: Exclude<AbilityName, 'none'>;
  scaleWithClassLevel?: FeatEffectScaling;
  isActive?: boolean;
}

export interface GrantsAbilityEffect {
  type: "grantsAbility";
  abilityKey: string;
  name: LocalizedString;
  details?: LocalizedString;
  uses?: GrantsAbilityEffectUses;
  actionType?: "standard" | "move" | "fullRound" | "free" | "swift" | "immediate" | "reaction" | "passive";
  scaleWithClassLevel?: FeatEffectScaling;
}

export interface ModifiesMechanicEffect {
  type: "modifiesMechanic";
  mechanicKey: string;
  change?: "adds" | "sets" | "removes";
  value?: any;
  scaleWithClassLevel?: FeatEffectScaling;
}

export interface GrantsProficiencyEffect {
  type: "grantsProficiency";
  proficiencyType: "weapon" | "armor" | "shield";
  itemCategory?: "simple" | "martial" | "exotic" | "light" | "medium" | "heavy" | "shield" | "tower"; // "shield" added to itemCategory
  specificItem?: string;
  note?: LocalizedString;
}

export interface BonusFeatSlotEffect {
  type: "bonusFeatSlot";
  category: string;
  count: number;
  note?: LocalizedString;
}

export interface LanguageEffect {
  type: "language";
  count?: number;
  specific?: LanguageId;
  note?: LocalizedString;
}

export interface DamageReductionFeatEffect {
  type: "damageReduction";
  drType: DamageReductionTypeValue | string;
  value: number;
  scaleWithClassLevel?: FeatEffectScaling;
}

export type FeatEffectDetail = (
  | SkillEffectDetail
  | NoteEffectDetail
  | AbilityScoreEffect
  | SavingThrowEffect
  | AttackRollEffect
  | DamageRollEffect
  | ArmorClassEffect
  | HitPointsEffect
  | InitiativeEffect
  | SpeedEffect
  | ResistanceEffect
  | CasterLevelCheckEffect
  | SpellSaveDcEffect
  | TurnUndeadEffect
  | GrantsAbilityEffect
  | ModifiesMechanicEffect
  | GrantsProficiencyEffect
  | BonusFeatSlotEffect
  | LanguageEffect
  | DamageReductionFeatEffect
) & Pick<AggregatedFeatEffectBase, 'condition' | 'sourceFeat'>;


export type FeatTypeString = string; // e.g., "general", "itemCreation", "metamagic"

export interface FeatDefinitionJsonData {
  id: string; // Unique identifier for the feat (kebab-case)
  label: LocalizedString;
  description?: LocalizedString;
  prerequisites?: FeatPrerequisiteDetails;
  effectsText?: LocalizedString;
  effects?: FeatEffectDetail[];
  canTakeMultipleTimes?: boolean;
  requiresSpecialization?: string;
  requiresSpecializationCategory?: string;
  isClassFeature?: boolean;
  isCustom?: boolean;
  category?: string;
  permanentEffect?: boolean;
  type?: FeatTypeString; // Added type field
}


export interface CharacterFeatInstance {
  definitionId: string; // ID of the FeatDefinitionJsonData
  instanceId: string; // Unique ID for this specific instance of the feat
  specializationDetail?: string;
  chosenSpecializationCategory?: string;
  isGranted?: boolean;
  grantedNote?: string;
  conditionalEffectStates?: Record<string, boolean>;
}

export type ItemBaseType = 'weapon' | 'armor' | 'shield' | 'potion' | 'scroll' | 'wand' | 'ring' | 'amulet' | 'boots' | 'belt' | 'bracers' | 'cloak' | 'gloves' | 'headband' | 'robe' | 'rod' | 'staff' | 'wondrous' | 'other';
export type WeaponStyleType = 'melee' | 'ranged' | 'melee-or-ranged';
export type WeaponProficiencyCategory = 'simple' | 'martial' | 'exotic';

export interface Item {
  id: string; // Unique ID for this item instance
  name: LocalizedString;
  quantity: number;
  description?: LocalizedString;
  weight?: number;
  itemType?: ItemBaseType;
  weaponType?: WeaponStyleType;
  damage?: string;
  criticalRange?: string;
  criticalMultiplier?: string;
  rangeIncrement?: number;
  damageType?: LocalizedString;
  isFinesseWeapon?: boolean;
  isLightWeapon?: boolean;
  isTwoHandedWeapon?: boolean;
  proficiencyCategory?: WeaponProficiencyCategory;
  specialProperties?: LocalizedString;
  armorBonus?: number;
  shieldBonus?: number;
  maxDexBonus?: number;
  armorCheckPenalty?: number;
  spellFailureChance?: number;
  speedWhenWorn?: number;
  armorType?: 'light' | 'medium' | 'heavy' | 'shield';
}


export type SavingThrowType = 'fortitude' | 'reflex' | 'will';

export interface SingleSavingThrow {
  base: number;
  magicMod: number;
  miscMod: number;
}
export interface SavingThrows {
  fortitude: SingleSavingThrow;
  reflex: SingleSavingThrow;
  will: SingleSavingThrow;
}

export interface ResistanceValue {
  base: number;
  customMod: number;
}

export type DamageReductionTypeValue = string;
export type DamageReductionRuleValue = string;

export interface DamageReductionInstance {
  id: string; // Unique ID for this DR instance
  value: number;
  type: DamageReductionTypeValue | string;
  rule: DamageReductionRuleValue;
  isGranted?: boolean;
  source?: LocalizedString;
}

export interface SpeedDetails {
  base: number;
  miscModifier: number;
}

export type CharacterSize =
  | "fine" | "diminutive" | "tiny" | "small" | "medium" | "large" | "huge" | "gargantuan" | "colossal" | '';

export type CharacterAlignment =
  | "lawful-good" | "neutral-good" | "chaotic-good"
  | "lawful-neutral" | "true-neutral" | "chaotic-neutral"
  | "lawful-evil" | "neutral-evil" | "chaotic-evil" | '';

export type DndRaceId = string; // kebab-case
export type DndClassId = string; // kebab-case
export type DndDeityId = string; // kebab-case or custom string
export type GenderId = string; // kebab-case for predefined, or custom string
export type LanguageId = string; // kebab-case
export type DomainId = string; // kebab-case
export type MagicSchoolId = string; // kebab-case


export interface LanguageOption {
  id: LanguageId; // Changed from value
  label: string;
}

export interface CharacterSizeObject {
  id: CharacterSize; // Changed from value
  label: string;
  acModifier: number;
  skillModifiers?: Record<string, number>;
  grappleDamage?: string;
}

export interface CharacterAlignmentObject {
  id: CharacterAlignment; // Changed from value
  label: string;
  description: string;
}

export interface ClassCastingDetails {
  type: 'full' | 'partial' | 'none';
  casterAbility?: Exclude<AbilityName, 'none' | 'strength' | 'dexterity' | 'constitution'>;
  startsAtLevel?: number;
  levelOffset?: number;
}

export interface ClassAttribute {
  key: string;
  value: string;
}

export interface ClassSpecificUIBlockConditionAggregatedEffect {
  property: keyof AggregatedFeatEffects;
  comparison: 'exists' | 'greaterThan' | 'equals' | 'lessThan' | 'notEquals';
  value?: any;
}

export interface ClassSpecificUIBlock {
  key: string;
  labelKey: string;
  requiredLevel?: number;
  conditionAggregatedEffect?: ClassSpecificUIBlockConditionAggregatedEffect;
  conditionDependsOnUIStateKey?: keyof Pick<Character, 'chosenSpecializationSchool'>;
  conditionDependsOnUIStateValueNotIn?: Array<string | null | undefined>;
}

export interface FeatChoiceFilterCase {
  choiceValue: string;
  noteMustContain: LocalizedString;
}

export interface FeatChoiceFilter {
  characterField: keyof Pick<Character, 'chosenCombatStyle'>;
  filterCases: FeatChoiceFilterCase[];
}

export interface DndRaceOption {
  id: DndRaceId; // Changed from value
  label: string;
  generalDescription?: string;
  loreAttributes?: ClassAttribute[];
  bonusFeatSlots?: number;
  racialSkillBonuses?: Record<string, number>;
  grantedFeats?: Array<{ featId: string; note?: string; name?: string; levelAcquired?: number }>;
  speeds?: Partial<Record<SpeedType, number>>;
  automaticLanguages?: LanguageId[];
}
export interface DndClassOption {
  id: DndClassId | string; // Changed from value
  label: string;
  hitDice: string;
  babProgression: "good" | "average" | "poor";
  spellcasting?: ClassCastingDetails;
  generalDescription: string;
  loreAttributes?: ClassAttribute[];
  grantedFeats?: Array<{ featId: string; note?: string; name?: string; levelAcquired?: number }>;
  saves?: {
    fortitude: "good" | "poor";
    reflex: "good" | "poor";
    will: "good" | "poor";
  };
  uiSections?: ClassSpecificUIBlock[];
  featChoiceFilters?: FeatChoiceFilter[];
  classSpecificFeats?: FeatDefinitionJsonData[];
}

export interface DeityAttribute {
  key: string;
  value: string;
}
export interface DndDeityOption {
  id: DndDeityId | string; // Changed from value
  label: string;
  alignment: CharacterAlignment | '';
  fullName: string;
  attributes: DeityAttribute[];
}

export interface SkillDefinitionJsonData {
  id: string; // Changed from value (kebab-case)
  label: string; // Already localized string
  keyAbility: AbilityName | string;
  description?: string; // Already localized string
  isCustom?: boolean; // Added for custom skill definitions
  providesSynergies?: CustomSynergyRule[]; // Added for custom skill definitions
}


export type ClassSkillsJsonData = Record<string, string[]>; // Key is class ID
export type ClassSkillPointsBaseJsonData = Record<string, number>; // Key is class ID
export type SynergyEffectJsonData = { targetSkill: string; ranksRequired: number; bonus: number; note?: LocalizedString }; // Added note
export type SkillSynergiesJsonData = Record<string, SynergyEffectJsonData[]>; // Key is skill ID

export interface CharacterFavoredEnemy {
  id: string; // Instance ID
  type: string;
  note?: string;
}
export interface DomainSpell {
  level: number;
  spellId: string; // ID of the spell
  spellName?: string; // Already localized string
}

export interface DomainDefinition {
  id: DomainId; // Changed from value
  label: string; // Already localized string
  description: string; // Already localized string
  grantedPowerDescription: string; // Already localized string
  grantedPowerFeatId?: string; // Feat ID
  domainSpells: DomainSpell[];
  deityAlignmentRestrictions?: CharacterAlignment[];
}

export interface MagicSchoolDefinition {
  id: MagicSchoolId; // Changed from value
  label: string; // Already localized string
  description?: string; // Already localized string
}

export interface CharacterAnimalCompanion {
  id: string; // Unique ID for this companion instance
  name?: string;
  type?: string; // e.g., "Wolf", "Hawk"
  notes?: string;
}

export interface Character {
  id: string; // Unique ID for the character
  name: string;
  playerName?: string;
  campaign?: string;
  homeland?: string;
  race: DndRaceId | ''; // ID of the race
  alignment: CharacterAlignment; // ID of the alignment
  deity?: DndDeityId | string; // ID of the deity or custom string
  size: CharacterSize; // ID of the size
  sizeModifierAttack?: number;
  age: number;
  gender: GenderId | string | ''; // ID of the gender or custom string
  height?: string;
  weight?: string;
  eyes?: string;
  hair?: string;
  skin?: string;
  languages?: LanguageId[]; // Array of language IDs
  experiencePoints?: number;
  abilityScores: AbilityScores;
  abilityScoreTempCustomModifiers: AbilityScores;
  hp: number;
  maxHp: number;
  baseMaxHp: number;
  customMaxHpModifier: number;
  nonlethalDamage: number;
  temporaryHp: number;
  numberOfWounds: number;
  armorBonus: number;
  shieldBonus: number;
  sizeModifierAC: number;
  naturalArmor: number;
  deflectionBonus: number;
  dodgeBonus: number;
  acMiscModifier: number;
  babMiscModifier: number;
  initiativeMiscModifier: number;
  grappleMiscModifier: number;
  grappleWeaponChoice: string;
  grappleDamage_baseNotes: string;
  grappleDamage_bonus: number;
  savingThrows: SavingThrows;
  classes: CharacterClass[]; // Each element's className is a DndClassId
  skills: Skill[]; // Each element's id is a Skill ID
  feats: CharacterFeatInstance[]; // Each element's definitionId is a Feat ID
  inventory: Item[];
  personalStory?: string;
  portraitDataUrl?: string;
  fireResistance: ResistanceValue;
  coldResistance: ResistanceValue;
  acidResistance: ResistanceValue;
  electricityResistance: ResistanceValue;
  sonicResistance: ResistanceValue;
  spellResistance: ResistanceValue;
  powerResistance: ResistanceValue;
  damageReduction: DamageReductionInstance[];
  fortification: ResistanceValue;
  landSpeed: SpeedDetails;
  burrowSpeed: SpeedDetails;
  climbSpeed: SpeedDetails;
  flySpeed: SpeedDetails;
  swimSpeed: SpeedDetails;
  armorSpeedPenalty_base: number;
  armorSpeedPenalty_miscModifier: number;
  loadSpeedPenalty_base: number;
  loadSpeedPenalty_miscModifier: number;
  chosenCombatStyle?: "archery" | "twoWeaponFighting";
  chosenFavoredEnemies?: CharacterFavoredEnemy[];
  chosenDomains?: [DomainId | undefined, DomainId | undefined]; // Array of Domain IDs
  chosenSpecializationSchool?: MagicSchoolId; // Magic School ID
  prohibitedSchools?: MagicSchoolId[]; // Array of Magic School IDs
  powerAttackValue?: number;
  combatExpertiseValue?: number;
  animalCompanion?: CharacterAnimalCompanion;
}

export type ResistanceFieldKeySheet = Exclude<keyof Pick<Character,
  'fireResistance' | 'coldResistance' | 'acidResistance' | 'electricityResistance' | 'sonicResistance' |
  'spellResistance' | 'powerResistance' | 'fortification'
>, 'damageReduction'>;

export type SpeedType = 'land' | 'burrow' | 'climb' | 'fly' | 'swim';

export interface ComboboxOption {
  value: string; // This 'value' is for the combobox component itself, usually populated by an 'id' from our data.
  label: string;
}

export interface GenericBreakdownItem {
  label: string;
  value: string | number;
  isBold?: boolean;
  isSubItem?: boolean;
  isRawValue?: boolean;
}

export type InfoDialogContentType =
  | { type: 'race' }
  | { type: 'class' }
  | { type: 'alignmentSummary' }
  | { type: 'deity' }
  | { type: 'abilityScoreBreakdown'; abilityName: Exclude<AbilityName, 'none'> }
  | { type: 'skillModifierBreakdown'; skillId: string } // skillId
  | { type: 'resistanceBreakdown'; resistanceField: ResistanceFieldKeySheet }
  | { type: 'acBreakdown'; acType: 'Normal' | 'Touch' | 'Flat-Footed' }
  | { type: 'babBreakdown' }
  | { type: 'initiativeBreakdown' }
  | { type: 'grappleModifierBreakdown' }
  | { type: 'grappleDamageBreakdown' }
  | { type: 'speedBreakdown'; speedType: SpeedType }
  | { type: 'armorSpeedPenaltyBreakdown' }
  | { type: 'loadSpeedPenaltyBreakdown' }
  | { type: 'savingThrowBreakdown'; saveType: SavingThrowType }
  | { type: 'maxHpBreakdown' }
  | { type: 'genericHtml'; title: string; content: string }
  | { type: 'genericNumericalBreakdown'; titleKey: keyof ProcessedSiteData['UI_STRINGS']; components: GenericBreakdownItem[] };


export interface SkillDefinitionForDisplay {
  id: string; // Skill ID
  name: string;
  keyAbility: AbilityName;
  description?: string;
  isCustom: boolean;
  providesSynergies?: CustomSynergyRule[];
}


export interface AbilityScoreComponentValue extends AggregatedFeatEffectBase {
  sourceLabel: string;
  sourceDetail?: string;
  value: number;
}
export interface AbilityScoreBreakdown {
  ability: Exclude<AbilityName, 'none'>;
  base: number;
  components: AbilityScoreComponentValue[];
  finalScore: number;
}
export type DetailedAbilityScores = Record<Exclude<AbilityName, 'none'>, AbilityScoreBreakdown>;

export interface AvailableFeatSlotsBreakdown {
  total: number;
  base: number;
  racial: number;
  classBonus: number;
  classBonusDetails: Array<{ category: string; count: number; sourceFeatLabel?: string }>;
}

export interface AggregatedFeatEffects {
  skillBonuses: Record<string, number>; // Key is Skill ID
  allSkillEffectDetails: Array<SkillEffectDetail & AggregatedFeatEffectBase>;
  favoredEnemyBonuses?: { skillBonus: number; damageBonus: number; };
  favoredEnemySlots?: number;
  abilityScoreBonuses: Array<AbilityScoreEffect & AggregatedFeatEffectBase>;
  savingThrowBonuses: Array<SavingThrowEffect & AggregatedFeatEffectBase>;
  attackRollBonuses: Array<AttackRollEffect & AggregatedFeatEffectBase>;
  damageRollBonuses: Array<DamageRollEffect & AggregatedFeatEffectBase>;
  acBonuses: Array<ArmorClassEffect & AggregatedFeatEffectBase>;
  hpBonus: number;
  hpBonusSources: Array<{ sourceFeatName: LocalizedString; value: number; condition?: string; isActive?: boolean; }>;
  initiativeBonus: number;
  speedBonuses: Array<SpeedEffect & AggregatedFeatEffectBase>;
  resistanceBonuses: Array<ResistanceEffect & AggregatedFeatEffectBase>;
  damageReductions: Array<DamageReductionFeatEffect & AggregatedFeatEffectBase>;
  casterLevelCheckBonuses: Array<CasterLevelCheckEffect & AggregatedFeatEffectBase>;
  spellSaveDcBonuses: Array<SpellSaveDcEffect & AggregatedFeatEffectBase>;
  turnUndeadBonuses: Array<TurnUndeadEffect & AggregatedFeatEffectBase>;
  grantedAbilities: Array<GrantsAbilityEffect & AggregatedFeatEffectBase & { uses?: GrantsAbilityEffectUses }>;
  modifiedMechanics: Record<string, AggregatedFeatEffectBase & { value?: any }>;
  proficienciesGranted: Array<GrantsProficiencyEffect & AggregatedFeatEffectBase>;
  bonusFeatSlots: Array<BonusFeatSlotEffect & AggregatedFeatEffectBase>;
  languagesGranted: {
      count: number;
      specific: Array<{ languageId: LanguageId; note?: string; sourceFeat?: LocalizedString; condition?: string; isActive?: boolean; }>;
  };
  descriptiveNotes: Array<(NoteEffectDetail) & AggregatedFeatEffectBase>;
  classLevels: Record<DndClassId, number>; // Class ID
}

export type CombatPanelCharacterData = Pick<Character,
  'abilityScores' | 'classes' | 'size' | 'inventory' | 'feats' |
  'babMiscModifier' | 'initiativeMiscModifier' | 'grappleMiscModifier' |
  'grappleDamage_baseNotes' | 'grappleDamage_bonus' | 'grappleWeaponChoice' |
  'sizeModifierAttack' | 'powerAttackValue' | 'combatExpertiseValue'
>;


export interface BabBreakdownDetails {
  baseBabFromClasses: number[];
  featAttackBonus: number;
  miscModifier: number;
  totalBab: number[];
  characterClassLabel?: string;
}
export interface InitiativeBreakdownDetails {
  dexModifier: number;
  featBonus: number;
  miscModifier: number;
  totalInitiative: number;
}
export interface GrappleModifierBreakdownDetails {
  baseAttackBonus: number;
  strengthModifier: number;
  sizeModifierGrapple: number;
  featBonus: number;
  miscModifier: number;
  totalGrappleModifier: number;
}
export interface GrappleDamageBreakdownDetails {
  baseDamage: string;
  strengthModifier: number;
  featBonus: number;
  bonus: number;
}
export interface SpeedComponent {
  source: string;
  value: number | string;
}
export interface SpeedBreakdownDetails {
  name: string;
  components: SpeedComponent[];
  total: number;
}

export interface PrerequisiteMessage {
  text: string;
  isMet: boolean;
  orderKey: string;
  originalText?: string;
}

export interface AcBreakdownDetailItem {
  mainLabel: string | React.ReactNode;
  value: string | number | React.ReactNode;
  isBold?: boolean;
  suffixDetails?: string[];
  type?: 'acAbilityMod' | 'acSizeMod' | 'acFeatBonus';
  abilityAbbr?: string;
  sizeName?: string;
  condition?: string;
  isActive?: boolean;
  isSubItem?: boolean;
}

export interface SavingThrowFeatComponent extends AggregatedFeatEffectBase {
  sourceFeat: string;
  value: number;
}

export interface SavingThrowBreakdownDetails {
  saveType: SavingThrowType;
  saveTypeLabel: string;
  baseSave: number;
  abilityKey: Exclude<AbilityName, 'none'> | undefined;
  abilityMod: number;
  magicMod: number;
  userTemporaryModifier: number;
  featBonusTotal: number;
  featComponents: SavingThrowFeatComponent[];
  totalSave: number;
}

export interface ProcessedSiteData {
  ALIGNMENTS: readonly CharacterAlignmentObject[];
  LANGUAGES: readonly LanguageOption[];
  XP_TABLE: readonly { level: number; xpRequired: number }[];
  EPIC_LEVEL_XP_INCREASE: number;
  SIZES: readonly CharacterSizeObject[];
  GENDERS: readonly { id: GenderId | string; label: string }[]; // Changed value to id
  DND_RACES: readonly DndRaceOption[];
  DND_CLASSES: readonly DndClassOption[];
  DND_DEITIES: readonly DndDeityOption[];
  DND_DOMAINS: readonly DomainDefinition[];
  DND_MAGIC_SCHOOLS: readonly MagicSchoolDefinition[];
  SKILL_DEFINITIONS: readonly SkillDefinitionJsonData[]; // Elements now use 'id'
  DND_FEATS_DEFINITIONS: readonly FeatDefinitionJsonData[]; // Elements now use 'id'
  FEAT_TYPES: readonly { id: FeatTypeString; label: string }[]; // Changed value to id
  ABILITY_LABELS: readonly { id: Exclude<AbilityName, 'none'>; label: string; abbr: string }[]; // Changed value to id
  SAVING_THROW_LABELS: readonly { id: SavingThrowType; label: string }[]; // Changed value to id
  DAMAGE_REDUCTION_TYPES: readonly { id: DamageReductionTypeValue; label: string }[]; // Changed value to id
  DAMAGE_REDUCTION_RULES_OPTIONS: readonly { id: string; label: string }[]; // Changed value to id
  ALIGNMENT_PREREQUISITE_OPTIONS: readonly { id: string; label: string }[]; // Changed value to id
  DEFAULT_ABILITIES: AbilityScores;
  DEFAULT_SAVING_THROWS: SavingThrows;
  DEFAULT_RESISTANCE_VALUE: ResistanceValue;
  DEFAULT_SPEED_DETAILS: SpeedDetails;
  DEFAULT_SPEED_PENALTIES: { armorSpeedPenalty_base: number; armorSpeedPenalty_miscModifier: number; loadSpeedPenalty_base: number; loadSpeedPenalty_miscModifier: number };
  DND_RACE_MIN_ADULT_AGE_DATA: Record<string, number>;
  DND_RACE_BASE_MAX_AGE_DATA: Record<string, number>;
  RACE_TO_AGING_CATEGORY_MAP_DATA: Record<string, string>;
  DND_RACE_AGING_EFFECTS_DATA: Record<string, { categories: Array<{ categoryName: string; ageFactor: number; effects: Record<string, number> }> }>;
  DND_RACE_ABILITY_MODIFIERS_DATA: Record<string, Partial<Record<Exclude<AbilityName, 'none'>, number>>>;
  DND_RACE_SKILL_POINTS_BONUS_PER_LEVEL_DATA: Record<string, number>;
  CLASS_SKILLS: Record<string, string[]>; // Key is class ID
  CLASS_SKILL_POINTS_BASE: Record<string, number>; // Key is class ID
  SKILL_SYNERGIES: Record<string, SynergyEffectJsonData[]>; // Key is skill ID
  UI_STRINGS: Record<string, string>;
}

export type FeatDefinitionWithEffects = FeatDefinitionJsonData & { effects: FeatEffectDetail[] };
export const isFeatWithEffects = (feat: FeatDefinitionJsonData): feat is FeatDefinitionWithEffects => {
  return Array.isArray(feat.effects) && feat.effects.length > 0;
};

export type CharacterUpdateField = keyof Character | `savingThrows.${keyof SavingThrows}.${'base'|'magicMod'|'miscMod'}` | `${ResistanceFieldKeySheet}.customMod` | 'damageReduction' | 'powerAttackValue' | 'combatExpertiseValue';

export { type AbilityScoreComponentValue };

export * from './character-core'; 
